version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo/sources
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Run tests
          command: npm run test

workflows:
  heroku_deploy:
    jobs:
      - build