version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/poc-cra-ci/sources/my-app
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: cd sources/my-app && npm ci
      - run:
          name: Run tests
          command: cd sources/my-app && npm run test

workflows:
  build:
    jobs:
      - build